In [ ]:
import pandas as pd

!wget https://course.ccs.neu.edu/cs6220/lecture-labs/lecture-3/abalone.csv

--2023-02-02 03:03:15--  https://course.ccs.neu.edu/cs6220/lecture-labs/lecture-3/abalone.csv
Resolving course.ccs.neu.edu (course.ccs.neu.edu)... 129.10.117.35
Connecting to course.ccs.neu.edu (course.ccs.neu.edu)|129.10.117.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 191962 (187K) [text/csv]
Saving to: ‘abalone.csv’

abalone.csv         100%[===================>] 187.46K  --.-KB/s    in 0.09s   

2023-02-02 03:03:15 (2.02 MB/s) - ‘abalone.csv’ saved [191962/191962]



# Read in Abalone data

In [ ]:
df = pd.read_csv("abalone.csv")

In [ ]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

# Explore the data

In this lab, you're going to drop features and scatter the points after projecting along 2 principle components axes.

For example, you may drop columns in `Pandas` by typing 


1. Prune the data. Drop columns `Sex` and/or `Rings`. \
   ```matrix = df.loc[:, df.columns != "Sex"]```

1. Calculate the covariance matrix. You can calculate the covariance matrix via: \
   $$Cov(X_i, X_j) = \mathbb{E}[(X_i - \mu_{x_i})(X_j - \mu_{x_j})^T]$$

1. Calculate the first two components of PCA. You can feel free to use `np.linalg.eig`.

1. Verify the principle components. To calculate PCA, feel free to use the PCA function from `scikit.learn`. \

  ```
  from sklearn.decomposition import PCA
  # Two components of PCA
  pca = PCA(2)

  # Fit on data
  pca.fit(A)

  # Access values and vectors
  print(pca.components_)
  print(pca.explained_variance_)

  # transform data
  B = pca.transform(A)
  print(B)
  ```

1. Scatter the data to view it in two dimensions

In [ ]:
data=df.loc[:,df.columns!="Sex"].to_numpy()
data

array([[ 0.455 ,  0.365 ,  0.095 , ...,  0.101 ,  0.15  , 15.    ],
       [ 0.35  ,  0.265 ,  0.09  , ...,  0.0485,  0.07  ,  7.    ],
       [ 0.53  ,  0.42  ,  0.135 , ...,  0.1415,  0.21  ,  9.    ],
       ...,
       [ 0.6   ,  0.475 ,  0.205 , ...,  0.2875,  0.308 ,  9.    ],
       [ 0.625 ,  0.485 ,  0.15  , ...,  0.261 ,  0.296 , 10.    ],
       [ 0.71  ,  0.555 ,  0.195 , ...,  0.3765,  0.495 , 12.    ]])

In [ ]:
data.shape

(4177, 8)

In [ ]:
cov = np.cov(data.T)
cov.shape


(8, 8)

In [ ]:
matrix = df.loc[:, df.columns != "Sex"]

In [ ]:

cov_matrix = pd.DataFrame.cov(df)
print(cov_matrix)

                  Length  Diameter    Height  Whole weight  Shucked weight  \
Length          0.014422  0.011761  0.004157      0.054491        0.023935   
Diameter        0.011761  0.009849  0.003461      0.045038        0.019674   
Height          0.004157  0.003461  0.001750      0.016803        0.007195   
Whole weight    0.054491  0.045038  0.016803      0.240481        0.105518   
Shucked weight  0.023935  0.019674  0.007195      0.105518        0.049268   
Viscera weight  0.011887  0.009787  0.003660      0.051946        0.022675   
Shell weight    0.015007  0.012507  0.004759      0.065216        0.027271   
Rings           0.215562  0.183872  0.075179      0.854409        0.301204   

                Viscera weight  Shell weight      Rings  
Length                0.011887      0.015007   0.215562  
Diameter              0.009787      0.012507   0.183872  
Height                0.003660      0.004759   0.075179  
Whole weight          0.051946      0.065216   0.854409  
Shucked

In [ ]:
import numpy as np
eig_values, eig_vectors = np.linalg.eig(cov_matrix)

In [ ]:
print("eig_vectors", eig_vectors)
print("eig_valuess", eig_values)

eig_vectors [[-2.10513202e-02  1.83052752e-01 -7.42040211e-01  9.06887398e-02
   3.07007218e-02 -6.18893826e-01  1.52311416e-01 -5.43508715e-03]
 [-1.79401219e-02  1.48804192e-01 -5.96175335e-01  4.20854302e-02
  -2.33409653e-02  7.83141972e-01  7.49734266e-02 -2.93613363e-02]
 [-7.31629638e-03  5.24595599e-02 -1.40358287e-01 -3.71173260e-02
  -1.45782231e-03 -4.21715859e-02 -9.10437257e-01 -3.81365645e-01]
 [-8.36804920e-02  8.34461310e-01  2.28847916e-01 -2.20616051e-01
   1.25570884e-01 -2.50039224e-03  1.82698066e-01 -3.82722100e-01]
 [-2.97346596e-02  3.99951598e-01  1.36354791e-01  7.54544047e-01
  -3.31709499e-01  5.43703582e-03 -1.68819392e-01  3.35655300e-01]
 [-1.74599170e-02  1.83252786e-01 -7.74498237e-03 -7.33235758e-02
   7.56051666e-01  2.91035964e-02 -2.30202123e-01  5.78984522e-01]
 [-2.74311519e-02  2.05272453e-01 -5.65032111e-02 -6.04242412e-01
  -5.48722324e-01 -3.15866047e-02 -1.65567109e-01  5.09217906e-01]
 [-9.95106815e-01 -9.79370973e-02  5.85253004e-03  1.1544

In [ ]:
from sklearn.decomposition import PCA
# Two components of PCA
pca = PCA(2)

# Fit on data
pca.fit(matrix)

# Access values and vectors
print(pca.components_)
print(pca.explained_variance_)

# transform data
B = pca.transform(matrix)
print(B)

[[ 0.02105132  0.01794012  0.0073163   0.08368049  0.02973466  0.01745992
   0.02743115  0.99510682]
 [ 0.18305275  0.14880419  0.05245956  0.83446131  0.3999516   0.18325279
   0.20527245 -0.0979371 ]]
[10.49543138  0.23926882]
[[ 5.00480331 -0.86692655]
 [-2.99106199 -0.43457164]
 [-0.94603495 -0.08673867]
 ...
 [-0.88806992  0.5087862 ]
 [ 0.0998919   0.34089986]
 [ 2.18474351  1.11378693]]


In [ ]:
from sklearn.decomposition import PCA
# Two components of PCA
pca = PCA(2)

# Fit on data
pca.fit(cov_matrix)

# Access values and vectors
print(pca.components_)
print(pca.explained_variance_)

# transform data
B = pca.transform(cov_matrix)
print(B)

[[ 0.01954924  0.01671871  0.00688318  0.07705125  0.02655607  0.01599492
   0.02578776  0.99585539]
 [ 0.17628835  0.14325778  0.05012205  0.83775272  0.40120045  0.18252174
   0.204184   -0.08994826]]
[1.29058996e+01 3.63417007e-03]
[[-1.35285698 -0.02409313]
 [-1.38544404 -0.03254284]
 [-1.49675853 -0.05646818]
 [-0.69679838  0.13701723]
 [-1.2621375   0.0285512 ]
 [-1.39054936 -0.02432441]
 [-1.28594222 -0.01822479]
 [ 8.87048701 -0.00991507]]
